apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nginxes.nginx.tsuru.io
spec:
  group: nginx.tsuru.io
  names:
    kind: Nginx
    listKind: NginxList
    plural: nginxes
    singular: nginx
  scope: Namespaced
  subresources:
    scale:
      labelSelectorPath: .status.podSelector
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.currentReplicas
    status: {}
  validation: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
