# Single replica nginx deploy
apiVersion: nginx.tsuru.io/v1alpha1
kind: Nginx
metadata:
  name: nginx-with-inline-config
spec:
  config:
    name: nginx-config
    kind: Inline
    value: |-
      events {}

      http {
        server {
          listen 8080;

          location / {
            return 200 'hello';
          }
        }
      }
